### ISSUE TITLE
Problem retrieving volume id at `GetEnergyInVolume`

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/geant4lib#99]
This problem was reported at https://rest-forum.unizar.es/t/performing-cuts-on-restg4-simulated-data/579/7

**Comment by jgalan** [comment]
Once the issue is solved I will add a validation check at the `04.MuonScan` example.

**Comment by lobis** [comment]
So after doing some digging I think I understad the problem.

In the `TRestGeant4Metadata` class we store information related to the volumes of the geometry: how many volumes, what are their names and ids etc. This is done for all volumes of the geometry.

Then in the detector section we specify the active volumes. Each active volume recieves an ID (which is not the same as the ID for the geometry volumes in general, as there may be less active volumes).

The analysis methods inside `TRestGeant4Event` take a `volID` parameter, which corresponds to the geometry volume ids (so these methods can be called for any volume in the simulation).

So I think everything works as intended but its confusing, I will update the `TRestGeant4Metadata::PrintMetadata` in order to print both the active volume id and the regular volume id which should be used in these methods (probably they should just use the name of the volume though, as there is no need to keep this complicated mapping of strings to ids, but it's deeply ingrained in the code so it's not easy to remove).

**Comment by jgalan** [comment]
Perhaps it would be easier to have a method where you add as argument a `std::string` with the name of the volume.

Would not be hard to make `GetFirstPositionInVolume( Int_t volID )` private, and implement a public method that used the human version `GetFirstPositionInVolume(std::string)` that retrieves the id from an initialised `std::map` that contains the volName - volId relations.

I always thought it was interesting to have `volID` method because this allows to iterate on all active volumes. However, this is not the case anymore, since the volId is related to all the geometry volumes, and not only the active volumes. So, perhaps, the method using a `volName` is more convenient.
